### ISSUE TITLE
Captive doesn't redirect on Android Chrome

### ISSUE THREAD

**Issue by mishoboss** [r-downing/PersWiFiManager#2]
Captive doesn't redirect on Android Chrome. It just stays on "redirecting...". On desktop Chrome works like a charm!

**Comment by r-downing** [comment]
Hmm it works fine for me. I'll do some tests on more devices and see if I can reproduce this. What version of Android is it?

Right now it's just set up to redirect to the root page "/" so if you don't have a root page or handler then it would be redirected in circles. But you say it works on desktop?

**Comment by r-downing** [comment]
Also, are you using the metaRefreshStr redirect from the example code? 

The "redirecting..." text should also be a hyperlink to the root page. Does it take you there if you click it manually?

**Comment by r-downing** [comment]
Maybe I'll try a javascript redirect instead. If you change the metaRefreshStr to something like

<body onload="javascript:window.location='/'">...

Would that work on your browser?

**Comment by r-downing** [comment]
Darn my above comment didn't display properly because I'm on mobile. I'll get back to it later

**Comment by r-downing** [comment]
Ok, I've put an updated version of the example, which uses a pure javascript redirect instead of the meta refresh. Seems to work fine for me. Let me know if that works on all your devices.

Thanks!

**Comment by r-downing** [comment]
I've added a new example sketch to this library that also uses my SPIFFSReadServer library with the js redirect incorporated

**Comment by r-downing** [comment]
I'm going to go ahead and mark this as closed, unless anyone else is still having issues?

**Comment by mishoboss** [comment]
Hi, sorry for delayed response. I've updated. Now its not working on desktop Chrome too!

Also there seems to be a blocking a few seconds after boot.

**Comment by r-downing** [comment]
Hmm, ok. Just to confirm, we're talking about the basic_rest_api.ino example? Did you upload the index.htm and wifi.htm pages from the data folder using the SPIFFS upload tool?

And you're saying it gets stuck on the page that says "redirecting..."? The word "redirecting..." should be a hyperlink. If you click that does it take you to the root page?

What versions of android and chrome are you using?

Do you have any ad-blocking installed, or something that disables javascript?

**Comment by r-downing** [comment]
Hmm, ok. Just to confirm, we're talking about the basic_rest_api.ino example? Did you upload the index.htm and wifi.htm pages from the data folder using the SPIFFS upload tool?

And you're saying it gets stuck on the page that says "redirecting..."? The word "redirecting..." should be a hyperlink. If you click that does it take you to the root page?

What versions of android and chrome are you using?

Do you have any ad-blocking installed, or something that disables javascript?



Also, for now it blocks while attempting to connect or change networks, but should proceed through the  program normally otherwise. I am planning to make this part non-blocking in the next version.

**Comment by mishoboss** [comment]
My bad. It works now! Thanks!

**Comment by r-downing** [comment]
Ok glad to hear! Thanks for the update
